"""create diagnostic cases

Revision ID: 1a1f63ce91f3
Revises: 
Create Date: 2026-09-14 16:31:56.566476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a1f63ce91f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_cases',
    sa.Column('case_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analysis_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='created', nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnostic_cases')
    # ### end Alembic commands ###
